config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "articles#index"
  resources :articles do
    resources :comments, only: [ :create, :destroy ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true
  validate :photo_type_and_size

  private

  def photo_type_and_size
    if photo.attached?
      if !photo.content_type.in?(%w(image/jpeg image/png))
        errors.add(:photo, 'must be a JPEG or PNG')
      elsif photo.blob.byte_size > 5.megabytes
        errors.add(:photo, 'size should be less than 5MB')
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :comments, dependent: :destroy
  # Регулярное выражение для проверки формата email и домена
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.(com|ru)\z/i

  # Валидация уникальности и правильности формата email
  validates :email, presence: true, uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX, message: "должен быть действительным и оканчиваться на .com или .ru" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  def index
    @articles = Article.all
  end

  def show
    # @article будет доступен здесь благодаря :set_article
  end

  # POST /articles
  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  # GET /articles/1/edit
  def edit
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :body, :published_at, :photo)
  end

  def authorize_user
    redirect_to(root_path, alert: 'Not authorized') unless @article.user == current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user! # Devise: требует, чтобы пользователь был аутентифицирован

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to article_path(@article), notice: 'Комментарий добавлен.'
    else
      redirect_to article_path(@article), alert: 'Ошибка при добавлении комментария.'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to article_path(@comment.article), notice: 'Комментарий удален.'
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
    def main

        @articles = Article.all
      end

      def show
        @article = Article.find(params[:id])
      end

      def new
        @article = Article.new
      end

      def create
        @article = Article.new(article_params)
        if @article.save
          redirect_to @article
        else
          render 'new'
        end
      end

      private
        def article_params
          params.require(:article).permit(:title, :body, :published_at)
        end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<div class="w-full flex justify-center mt-10 min-h-5/6 flex-col items-center">
  <div class="space-y-4 border-2 border-gray-500 px-7 py-5  w-6/12 xl:w-3/12 rounded-xl text-center shadow-2xl bg-white/0">
    <%= form_with(model: @article, local: true) do |form| %>
      <div class="space-y-3">
        <% if @article.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
            <ul>
              <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field space-y-1">
          <%= form.label :title, :class=>"text-lg block" %>
          <%= form.text_field :title %>
        </div>

        <div class="field space-y-1">
          <%= form.label :body, :class=>"text-lg block" %>
          <%= form.text_area :body %>
        </div>

        <div class="field space-y-1">
          <%= form.label :photo, :class=>"text-lg block" %>
          <%= form.file_field :photo %>
        </div>

        <div class="actions">
          <%= form.submit class: 'border border-black p-2 bg-gray-300 cursor-pointer w-5/6 rounded-full mt-4 translate hover:bg-gray-300/60 mb-12' %>
        </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="flex flex-col justify-center px-10">
    <h1 class="font-bold text-2xl text-center">Edit Article</h1>
    <%= render 'articles/form', article: @article %>
    <%= link_to 'Back', article_path(@article), class: '-mt-12 p-2 text-blue-500 hover:underline transition-all' %>
</div>

app/views/articles/index.html.erb
<div class="flex flex-col justify-center px-10">
  <h1 class="font-bold text-2xl text-center">Articles</h1>
  
  <%= link_to 'New Article', new_article_path, class: "ml-auto p-2 bg-black/0 border border-black shadow-[0_0_10px_4px] shadow-black/10 hover:shadow-[5px_6px_20px_4px] hover:shadow-black/30 hover:bg-gray-400/60 transition-all rounded-2xl"  %>
</div>
<div class="px-10  py-10 grid rows-2 grid-cols-3 gap-10">
  <% @articles.each do |article| %>
      <%= link_to article, class: "bg-white hover:opacity-60 transition-all hover:shadow-[0_0_20px_8px] w-fit rounded-xl flex flex-col gap-2  shadow-black/10 shadow-[0_0_10px_4px] pb-5 cursor-pointer " do%>
          <% if article.photo.attached? %>
            <%= image_tag(article.photo, class: 'rounded-t-xl aspect-[4/3] min-h-[80%]') %>
          <% else %>
            <%= image_tag('/erus.jpg', class: 'rounded-t-xl aspect-[4/3] min-h-[80%]') %>
          <% end %>

        <p class="text-xl px-5 font-bold truncate "><%= article.title %></p>
        <p class="text-gray-400 px-5"><%= article.created_at.strftime("%d %B") %></p>
    <% end %>
  <% end %>

</div>

app/views/articles/new.html.erb
<div class="flex flex-col justify-center px-10">
    <h1 class="font-bold text-2xl text-center">New Article</h1>
<%= render 'articles/form', article: @article %>
<%= link_to 'Back', articles_path, class: '-mt-12 p-2 text-blue-500 hover:underline transition-all' %>
</div>

app/views/articles/show.html.erb
<div class="flex flex-col justify-center px-10 text-center gap-2">
<div class="grid grid-cols-[1fr_2fr_1fr]">
  <div class="w-fit">
  <%= link_to articles_path, class: 'hover:opacity-60 flex' do %>
    <%= image_tag('/back.svg', size: '20x20') %>
    Back
  <% end %>
  </div>
  <h1 class="font-bold text-2xl text-center"><%= @article.title %></h1>
<div class="buttonsBlock ml-auto flex gap-2 items-center">
  <% if user_signed_in? && @article.user == current_user %>
    <%= link_to edit_article_path(@article), class: 'hover:opacity-60 flex justify-center items-center' do %>
      <%= image_tag('/pen-square.svg', size: '20x20') %>
      Edit
    <% end %>

    <%= form_with url: article_path(@article), method: :delete, local: true, class: "h-fit" do %>
      <%= button_tag(type: 'submit', data: { confirm: 'Вы уверены?' }, class: 'hover:opacity-60 text-red-500 flex items-center') do %>
        <%= image_tag('/delete-2.svg', size: '20x20', class: 'mr-2') %>
        Destroy
      <% end %>
    <% end %>



    <%#= link_to @article, method: :delete, data: { confirm: 'Are you sure?' }, class: 'hover:opacity-60 text-red-500 flex justify-center items-center' do %>
      <%#= image_tag('/delete-2.svg', size: '20x20') %>
<!--      Destroy-->
    <%# end %>
  <% end %>
</div>
</div>
<div class="flex flex-col gap-10 px-32">
  <p class="text-center text-sm">Published at: <%= @article.created_at.strftime("%m.%d.%Y") %></p>

    <% if @article.photo.attached? %>
        <%= image_tag @article.photo, class: 'min-w-96 mx-auto rounded-lg' %>
    <% end %>
    <p class=""><%= @article.body %></p>
    <span class="text-start ">Author: <%= @article.user.email %></span>
    <div class="flex gap-2">
      <button onclick="share(event)" class="hover:opacity-60 transition-opacity" title="vk" data-social='vk'>
        <%= image_tag('/vk-v2.svg', size: '40x40') %>
      </button>
      <button onclick="share(event)" class="hover:opacity-60 transition-opacity" title="whats`app" data-social='wa'>
        <%= image_tag('/whatsapp-color.svg', size: '40x40') %>
      </button>
      <button onclick="share(event)" class="hover:opacity-60 transition-opacity" title="ok" data-social='ok'>
        <%= image_tag('/odnoklassniki.svg', size: '40x40') %>
      </button>
      <button onclick="share(event)" class="hover:opacity-60 transition-opacity" title="telegram" data-social='tg'>
        <%= image_tag('/telegram.svg', size: '40x40') %>
      </button>
      <div>
        <button onclick="copyToClipboard()" class="hover:opacity-60 transition-opacity" title="copy">
          <%= image_tag('/copy.svg', size: '40x40') %>
        </button>
      </div>
    </div>
  </div>




  <div class="mx-24  mb-10 space-y-4" >
    <h3>Сообщений: <%= @article.comments.length %></h3>
    <%= render @article.comments %>
    <% if user_signed_in? %>
      <%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
        <% if @comment && @comment.errors.any? %>
          <div class="error_messages">
            <h2><%= pluralize(@comment.errors.count, "ошибка") %> запрещают сохранение комментария:</h2>
            <ul>
              <% @comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field flex items-center border border-gray-500 rounded-md bg-white">
          <%= form.text_area :content, placeholder: "Enter your comment...", class: "flex-1 min-h-20 border-none rounded-l-md bg-transparent resize-y", required: true %>
          <%= form.submit "Create comment", :type => :image, :src => "/back.svg", :class => 'cursor-pointer rounded-r-md w-7 h-20 hover:bg-green-600/60 transition-colors p-1 bg-green-600 rotate-180' %>
        </div>
      <% end %>
    <% else %>
      <p>Пожалуйста, <%= link_to 'войдите', new_user_session_path, class: 'hover:underline hover:text-blue-400 transition-all' %> или <%= link_to 'зарегистрируйтесь', new_user_registration_path, class: 'hover:underline hover:text-blue-400 transition-all' %>, чтобы добавить комментарий.</p>
    <% end %>
  </div>
</div>

<script>
  function copyToClipboard() {
    navigator.clipboard.writeText(window.location.href)
    alert("Ссылка скопирована")
  }
  function share(e){
    var url_soc = false;
    switch (e.currentTarget.dataset.social) {
        case "vk":
            url_soc = "https://vk.com/share.php?url="+window.location.href;
            break;
        case "ok":
            url_soc = "https://connect.ok.ru/offer?url="+window.location.href;
            break;
        case "wa":
            url_soc = "https://api.whatsapp.com/send/?text="+window.location.href;
            break;
        case "tg":
            url_soc = "https://t.me/share/url?url="+window.location.href;
            break;
    }
    
    if(url_soc){
        var width = 800, height = 500;
        var left = (window.screen.width - width) / 2;
        var top = (window.screen.height - height) / 2;
        const social_window = window.open(url_soc, "share_window", "height=" + height + ",width=" + width + ",top=" + top + ",left=" + left);
        social_window.focus();
    }
  }
</script>

app/views/comments/_comment.html.erb
<div class="space-y-4 mx-auto border p-2 rounded-2xl shadow-xl border-black/80 w-8/12">
  <div class="title text-start">
    <strong>
      <%= comment.user.email %>
    </strong>
    <%= comment.created_at.strftime('%d.%m.%y, %H:%M') %>
  </div>
  <div class="seporator h-px w-full border border-gray-400"></div>
  <div class="body text-start">

    <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
    <%= form_with url: article_comment_path(comment.article, comment), method: :delete do %>
      <%= submit_tag 'Удалить', data: { confirm: 'Вы уверены?' } %>
    <% end %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "News Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-gray-200/50 flex flex-col min-h-screen">
    <header class="self-start px-10 bg-black/40 grid grid-cols-[14rem_1fr_14rem] justify-items-center items-center w-full">
      <%= link_to root_path, class: "w-fit justify-self-start hover:opacity-60 transition-all font-bold text-3xl text-center content-center" do %>
        <img class="avatar size-8 py-1 h-full" src="/headerIcon.svg" alt="Logo" />
      <% end %>
      <%= link_to "News", root_path, class: "w-fit text-center hover:opacity-60 transition-all font-bold text-3xl text-center content-center" %>
      <div class="login">
        <% if user_signed_in? %>
          <div class="flex gap-1 items-center">
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'adf p-2 bg-white rounded-2xl shadow-[inset_0_2px_20px_4px] shadow-black/20 border-black border-1 hover:bg-white/60 transition-colors' %>
            <span>|</span>
            <%= form_for(:destroy_user_session, url: destroy_user_session_path, method: :delete, html: {class: 'logout-form'}) do %>
              <%= submit_tag 'Logout', class: 'cursor-pointer adf p-2 bg-red-400 shadow-[0_2px_10px_4px] shadow-black/10 border-black/40 border rounded-2xl hover:bg-red-400/60 transition-colors' %>
            <% end %>
          </div>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, :class => "adf p-2 bg-white rounded-2xl shadow-[inset_0_2px_20px_4px] shadow-black/20 border-black border-1 hover:bg-white/60 transition-colors" %> |
          <%= link_to 'Login', new_user_session_path, :class => "adf p-2 bg-green-400 shadow-[0_2px_10px_4px] shadow-black/10 border-black/40 border rounded-2xl hover:bg-green-400/60 transition-colors" %>
        <% end %>
      </div>
    </header>
    <main class=" mb-3 mt-2">
      <%= yield %>
    </main>
    <footer class="mt-auto py-9 bg-gray-300 text-3xl font-bold text-center" >
      Здесь лежит футер я его не придумал
    </footer>
  </body>
</html>

app/views/news/main.html.erb
<div class="px-10  py-10 grid rows-2 grid-cols-3 gap-10">
    <%= link_to @article, class: "bg-white hover:opacity-60 transition-all hover:shadow-[0_0_20px_8px] w-fit rounded-xl flex flex-col gap-2  shadow-black/10 shadow-[0_0_10px_4px] pb-5 cursor-pointer " do %>
        <img class="rounded-t-xl  aspect-[4/3]" src="/erus.jpg" alt="news_img">
        <p class="text-xl px-5 font-bold truncate ">Text about something....</p>
        <p class="text-gray-400 px-5">20 august</p>
    <% end %>
    <%= link_to @article, class: "bg-white hover:opacity-60 transition-all hover:shadow-[0_0_20px_8px] w-fit rounded-xl flex flex-col gap-2  shadow-black/10 shadow-[0_0_10px_4px] pb-5 cursor-pointer " do %>
        <img class="rounded-t-xl  aspect-[4/3]" src="/erus.jpg" alt="news_img">
        <p class="text-xl px-5 font-bold truncate ">Text about something....</p>
        <p class="text-gray-400 px-5">20 august</p>
    <% end %>
    <%= link_to @article, class: "bg-white hover:opacity-60 transition-all hover:shadow-[0_0_20px_8px] w-fit rounded-xl flex flex-col gap-2  shadow-black/10 shadow-[0_0_10px_4px] pb-5 cursor-pointer " do %>
        <img class="rounded-t-xl  aspect-[4/3]" src="/erus.jpg" alt="news_img">
        <p class="text-xl px-5 font-bold truncate ">Text about something....</p>
        <p class="text-gray-400 px-5">20 august</p>
    <% end %>
    <%= link_to @article, class: "bg-white hover:opacity-60 transition-all hover:shadow-[0_0_20px_8px] w-fit rounded-xl flex flex-col gap-2  shadow-black/10 shadow-[0_0_10px_4px] pb-5 cursor-pointer " do %>
        <img class="rounded-t-xl  aspect-[4/3]" src="/erus.jpg" alt="news_img">
        <p class="text-xl px-5 font-bold truncate ">Text about something....</p>
        <p class="text-gray-400 px-5">20 august</p>
    <% end %>
    <%= link_to @article, class: "bg-white hover:opacity-60 transition-all hover:shadow-[0_0_20px_8px] w-fit rounded-xl flex flex-col gap-2  shadow-black/10 shadow-[0_0_10px_4px] pb-5 cursor-pointer " do %>
        <img class="rounded-t-xl  aspect-[4/3]" src="/erus.jpg" alt="news_img">
        <p class="text-xl px-5 font-bold truncate ">Text about something....</p>
        <p class="text-gray-400 px-5">20 august</p>
    <% end %>
    <%= link_to @article, class: "bg-white hover:opacity-60 transition-all hover:shadow-[0_0_20px_8px] w-fit rounded-xl flex flex-col gap-2  shadow-black/10 shadow-[0_0_10px_4px] pb-5 cursor-pointer " do %>
        <img class="rounded-t-xl  aspect-[4/3]" src="/erus.jpg" alt="news_img">
        <p class="text-xl px-5 font-bold truncate ">Text about something....</p>
        <p class="text-gray-400 px-5">20 august</p>
    <% end %>
</div>